
--
-- Table structure for table `medecins`
--

DROP TABLE IF EXISTS `medecins`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE medecins (
  id                integer           not null,
  nom varchar(5) DEFAULT NULL,
  prenom varchar(40) DEFAULT NULL,
  code_postal varchar(7) DEFAULT NULL,
  localite varchar(11) DEFAULT NULL,
  constraint PK_medcin primary key (id)
) 


INSERT INTO medecins (Nom, Prenom, Commune, CodePostal) VALUES 
('Adam', 'Rina', 'Bouffioulx', '6200'),
('Adriaensen', 'Muriel', 'Gerpinnes', '6280'),
('Aktas', 'Haydar', 'Marchienne-au-Pont', '6030'),
('Alafakis', 'Grégory', 'Courcelles', '6180'),
('Allard', 'Jean-Paul', 'Nalinnes', '6120'),
('Allot', 'Charlotte', 'Couillet', '6010'),
('Alvarez', 'Walter', 'Montignies-sur-Sambre', '6061'),
('Ameziane', 'Sarah', 'Mont-sur-Marchienne', '6032'),
('Amico', 'Alessandro', 'Bouffioulx', '6200'),
('Amri', 'Sabrine', 'Charleroi', '6000'),
('Andre', 'Willy', 'Lobbes', '6540'),
('Andris', 'Stéphanie', 'Laneffe', '5651'),
('Angiolillo', 'David', 'Lambusart', '6220'),
('Aslan', 'Haftane', 'Aiseau-Presles', '6250'),
('Asmat', 'Monazzah', 'Charleroi', '6000'),
('Aubry', 'Thierry', 'Somzée', '5651'),
('Ayoub', 'Damien', 'Frasnes-lez-Gosselies', '6210'),
('Badalamenti', 'Anthony', 'Walcourt', '5650'),
('Baddich', 'Kadija', 'Marcinelle', '6001'),
('Badot', 'Jean-Louis', 'Jumet', '6040'),
('Baivier', 'François', 'Montignies-sur-Sambre', '6061'),
('Baligant', 'Michel', 'Fleurus', '6220'),
('Bambara', 'Jerry', 'Charleroi', '6000'),
('Barbason', 'Emmanuelle', 'Montigny-le-Tilleul', '6110'),
('Barbason', 'Xavier', 'Lodelinsart', '6042'),
('Barbeaux', 'Valentine', 'Roux', '6044'),
('Barboni', 'Tiziana', 'Marcinelle', '6001'),
('Barracho', 'Carlos', 'Bouffioulx', '6200'),
('Bastien', 'Camille', 'Frasnes-lez-Gosselies', '6210'),
('BASTIN', 'France', 'Arquennes', '7181'),
('Baudoux', 'Benjamin', 'Pont-de-Loup', '6250'),
('Baudoux', 'Pierre', 'Pont-de-Loup', '6250'),
('Bayot', 'Marine', 'Leernes', '6142'),
('Beloy', 'Stéphane', 'Jumet', '6040'),
('Benabderrazik', 'Amine', 'Fleurus', '6220'),
('Benali', 'Elias', 'Charleroi', '6000'),
('Benjelloun', 'Sonia', 'Pironchamps', '6240'),
('Benzerroug', 'Abdelhamid', 'Charleroi', '6000'),
('Bergez', 'Christophe', 'Nalinnes', '6120'),
('Berti', 'Floriano', 'Marchienne-au-Pont', '6030'),
('Bets', 'Pierre', 'Jumet', '6040'),
('Beuken', 'Sophie', 'Dampremy', '6020'),
('Bienaime', 'Jovenel', 'Marchienne-au-Pont', '6030'),
('Bierlaire', 'Kevin', 'Montignies-sur-Sambre', '6061'),
('Bigonville', 'Sophie', 'Souvret', '6182'),
('Bingana Ndjomo', 'Barnabé', 'Aiseau', '6250'),
('Blase', 'Franz', 'Aiseau-Presles', '6250'),
('Blazinsek', 'Orlando', 'Courcelles', '6180'),
('Bochouari', 'Aicha', 'Dampremy', '6020'),
('Bochouari', 'Halima', 'Dampremy', '6020'),
('Bochouari', 'Omar', 'Dampremy', '6020'),
('Bochouari', 'Zineb', 'Dampremy', '6020'),
('Boland', 'Camille', 'Courcelles', '6180'),
('Bombled', 'Philippe', 'Thuillies', '6536'),
('Bonvissuto', 'Elise', 'Marchienne-Docherie', '6030'),
('Borlee', 'Frédéric', 'Anderlues', '6150'),
('Borremans', 'Isabelle', 'Courcelles', '6180'),
('Bouazza', 'Nour', 'Obaix', '6230'),
('Bouchat', 'Nadine', 'Nalinnes', '6120'),
('Bourgeois', 'Stéphane', 'Piéton', '7160'),
('Boutaher', 'Elias', 'Marchienne-Docherie', '6030'),
('Bouvy', 'Stephanie', 'Montignies-sur-Sambre', '6061'),
('Bouyaddou', 'Hamza', 'Courcelles', '6180'),
('Boxus', 'Baudouin', 'Gilly', '6060'),
('Brahmi', 'Mohamed', 'Marchienne-au-Pont', '6030'),
('Breton', 'Jean-Luc', 'Mellet', '6211'),
('Briclet', 'Jacques', 'Thiméon', '6230'),
('Briclet', 'Marie', 'Gerpinnes', '6280'),
('Brichaux', 'Jacques', 'Courcelles', '6180'),
('Brisbois', 'David', 'Charleroi', '6000'),
('Brisebois', 'Benoit', 'Frasnes-lez-Gosselies', '6210'),
('Brison', 'Léon', 'Anderlues', '6150'),
('BRODKOM', 'Nancy', 'Anderlues', '6150'),
('Broly', 'Aurore', 'Anderlues', '6150'),
('Broly', 'Bernard', 'Anderlues', '6150'),
('Broly', 'Florian', 'Anderlues', '6150'),
('Bruggeman', 'Gaëtan', 'Charleroi', '6000'),
('Bruyneel', 'Aurélie', 'Nalinnes', '6120'),
('Bruyneel', 'Catherine', 'Loverval', '6280'),
('Bruyneel', 'Valérie', 'Châtelineau', '6200'),
('Buard', 'Alexandre', 'Marchienne-au-Pont', '6030'),
('Buczek', 'Marc', 'Loverval', '6280'),
('Bukasa', 'Rosine', 'Anderlues', '6150'),
('Burdzy', 'Maria', 'Montigny-le-Tilleul', '6110'),
('Burlet', 'Pierre', 'Nalinnes', '6120'),
('Cabeke', 'Murielle', 'Charleroi', '6000'),
('Calomme', 'Olivier', 'Charleroi', '6000'),
('Cantarella', 'Frédéric', 'Mont-sur-Marchienne', '6032'),
('Carion', 'Gauthier', 'Villers-Perwin', '6210'),
('Carion', 'Stéphanie', 'Villers-Perwin', '6210'),
('Carlino', 'Filippo', 'Montignies-sur-Sambre', '6061'),
('Caro', 'Federico', 'Charleroi', '6000'),
('Carrer', 'Annick', 'Bouffioulx', '6200'),
('Castro', 'Ana', 'Charleroi', '6000'),
('Catton', 'Fanny', 'Loverval', '6280'),
('Cauvin', 'Alexandra', 'Gouy-lez-Piéton', '6181'),
('Cavaleri', 'Frédéric', 'Gosselies', '6041'),
('Cavaleri', 'Ophélie', 'Charleroi', '6000'),
('Cavaleri', 'Vittorio', 'Gosselies', '6041'),
('Celis', 'Alain', 'Anderlues', '6150'),
('Cerioli', 'Barbara', 'Charleroi', '6000'),
('Cerioli', 'Jean-Marie', 'Charleroi', '6000'),
('Chaidron', 'Jean-Paul', 'Courcelles', '6180'),
('Champagnat', 'François', 'Lodelinsart', '6042'),
('Charlier', 'Alexandre', 'Charleroi', '6000'),
('Charlier', 'Catherine', 'Pont-à-Celles', '6230'),
('Charlier', 'Christophe', 'Frasnes-lez-Gosselies', '6210'),
('Charlier', 'Géraldine', 'Frasnes-lez-Gosselies', '6210'),
('Charlier', 'Marc', 'Gerpinnes', '6280'),
('Charlier', 'Mathieu', 'Montignies-sur-Sambre', '6061'),
('Charlier', 'Thibault', 'Charleroi', '6000'),
('Charlier', 'Vincent', 'Frasnes-lez-Gosselies', '6210'),
('Charlier', 'Viviane', 'Châtelineau', '6200'),
('Chauvin', 'Thierry', 'Jumet', '6040'),
('Chauviré', 'Julie', 'Loverval', '6280'),
('Chedoeuf', 'Maxime', 'Montignies-sur-Sambre', '6061'),
('Cheron', 'Alain', 'Jumet', '6040'),
('Cheron', 'Martine', 'Jumet', '6040'),
('Chicoteau', 'Jonathan', 'Gerpinnes', '6280'),
('Chicoteau', 'Sylvie', 'Gerpinnes', '6280'),
('Chikh', 'Larbi', 'Marchienne-au-Pont', '6030'),
('Chwastek', 'Olivier', 'Gerpinnes', '6280'),
('Ciccarelli', 'Daniele', 'Montignies-sur-Sambre', '6061'),
('Ciccarelli', 'Paolo', 'Montignies-sur-Sambre', '6061'),
('Cipolletta', 'Carlo', 'Courcelles', '6180'),
('Clarinval', 'Lorenzo', 'Couillet', '6010'),
('Claude', 'Alexandre', 'Lodelinsart', '6042'),
('Claude', 'Jean-François', 'Frasnes-lez-Gosselies', '6210'),
('Claude', 'Jérôme', 'Gosselies', '6041'),
('Claude', 'Valérie', 'Lodelinsart', '6042'),
('Clausse', 'Nicolas', 'Gilly', '6060'),
('Clausse', 'Romain', 'Gilly', '6060'),
('Clerbois', 'Laurence', 'Anderlues', '6150'),
('Clerbois', 'Ludovic', 'Anderlues', '6150'),
('Clerbois', 'Pascal', 'Anderlues', '6150'),
('Clerbois', 'Pierre', 'Anderlues', '6150'),
('Closset', 'Yves', 'Loverval', '6280'),
('Closon', 'Nathalie', 'Frasnes-lez-Gosselies', '6210'),
('Cocco', 'Nicolas', 'Charleroi', '6000'),
('Coelho', 'Edouard', 'Charleroi', '6000'),
('Coletti', 'Angelo', 'Gosselies', '6041'),
('Coletti', 'Evelyne', 'Gosselies', '6041'),
('Collard', 'Cécile', 'Montignies-sur-Sambre', '6061'),
('Collart', 'Pierre', 'Montigny-le-Tilleul', '6110'),
('Collart', 'Sylvain', 'Montigny-le-Tilleul', '6110'),
('Collette', 'Christophe', 'Courcelles', '6180'),
('Collette', 'Francis', 'Montignies-sur-Sambre', '6061'),
('Collette', 'François', 'Gosselies', '6041'),
('Collette', 'Pascal', 'Montignies-sur-Sambre', '6061'),
('Collette', 'Sophie', 'Gosselies', '6041'),
('Collette', 'Thierry', 'Gosselies', '6041'),
('Comanne', 'Florence', 'Gosselies', '6041'),
('Comblain', 'Laurent', 'Charleroi', '6000'),
('Comhaire', 'Catherine', 'Courcelles', '6180'),
('Conde', 'Antoine', 'Charleroi', '6000'),
('Confino', 'Laurent', 'Charleroi', '6000'),
('Consiglio', 'Teresa', 'Courcelles', '6180'),
('Coppée', 'Evelyne', 'Gosselies', '6041'),
('Coppée', 'Philippe', 'Gosselies', '6041'),
('Corbisier', 'David', 'Charleroi', '6000'),
('Cordaro', 'Michaël', 'Gerpinnes', '6280'),
('Cornez', 'Nicolas', 'Couillet', '6010'),
('Cornil', 'Aurore', 'Marchienne-au-Pont', '6030'),
('Coron', 'Renaud', 'Gerpinnes', '6280'),
('Corroy', 'Françoise', 'Frasnes-lez-Gosselies', '6210'),
('Corroy', 'Laurent', 'Frasnes-lez-Gosselies', '6210'),
('Cousin', 'Yannick', 'Montignies-sur-Sambre', '6061'),
('Cousin', 'Yannick', 'Montignies-sur-Sambre', '6061'),
('Cox', 'Philippe', 'Gouy-lez-Piéton', '6181'),
('Crenier', 'Aurore', 'Gerpinnes', '6280'),
('Crenier', 'François', 'Gerpinnes', '6280'),
('Crépin', 'Gilles', 'Nalinnes', '6120'),
('Crutzen', 'Philippe', 'Jumet', '6040'),
('Cuffaro', 'Angelo', 'Marchienne-au-Pont', '6030'),
('Cuvelier', 'Axel', 'Charleroi', '6000'),
('Cuvelier', 'Cécile', 'Jumet', '6040'),
('Cuvelier', 'Christophe', 'Charleroi', '6000'),
('Cuvelier', 'David', 'Charleroi', '6000'),
('Cuvelier', 'Guy', 'Chapelle-lez-Herlaimont', '7160'),
('Cuvelier', 'Guy', 'Châtelet', '6200'),
('Cuvelier', 'Jean-Michel', 'Gerpinnes', '6280'),
('Cuvelier', 'Jérôme', 'Jumet', '6040'),
('Cuvelier', 'Ludovic', 'Montignies-sur-Sambre', '6061'),
('Cuvelier', 'Michel', 'Courcelles', '6180'),
('Cuvelier', 'Michel', 'Frasnes-lez-Gosselies', '6210'),
('Cuvelier', 'Olivier', 'Charleroi', '6000'),
('Cuvelier', 'Patricia', 'Montignies-sur-Sambre', '6061'),
('Cuvelier', 'Philippe', 'Charleroi', '6000'),
('Cuvelier', 'Serge', 'Courcelles', '6180'),
('Cuvelier', 'Thierry', 'Charleroi', '6000'),
('Cuvelier', 'Xavier', 'Montignies-sur-Sambre', '6061'),
('Cuvelier', 'Yannick', 'Frasnes-lez-Gosselies', '6210'),
('Cuypers', 'Alain', 'Anderlues', '6150'),
('Cuypers', 'Gilles', 'Anderlues', '6150'),
('D\'amario', 'Géraldine', 'Loverval', '6280'),
('D`avino', 'Domenico', 'Montignies-sur-Sambre', '6061'),
('Dahbi', 'Abdelkrim', 'Gilly', '6060'),
('Damiens', 'Christophe', 'Montignies-sur-Sambre', '6061'),
('Damy', 'Catherine', 'Montignies-sur-Sambre', '6061'),
('Dangreau', 'Isabelle', 'Courcelles', '6180'),
('Daras', 'Laurence', 'Gilly', '6060'),
('Darimont', 'Jean-François', 'Frasnes-lez-Gosselies', '6210'),
('Darimont', 'Pierre', 'Gosselies', '6041'),
('Darimont', 'Sébastien', 'Gosselies', '6041'),
('Darnois', 'Jean-Claude', 'Gerpinnes', '6280'),
('Dasseleer', 'Frédéric', 'Gosselies', '6041'),
('Dasseleer', 'Philippe', 'Gosselies', '6041'),
('Dassonville', 'François', 'Loverval', '6280'),
('Daumerie', 'David', 'Marchienne-Docherie', '6030'),
('Daumerie', 'Fabrice', 'Marchienne-Docherie', '6030'),
('Daveloose', 'Jean-Luc', 'Gosselies', '6041'),
('De Backer', 'Luc', 'Gosselies', '6041'),
('De Bie', 'Mickaël', 'Montignies-sur-Sambre', '6061'),
('De Block', 'Fanny', 'Charleroi', '6000'),
('De Bodt', 'Laurent', 'Montigny-le-Tilleul', '6110'),
('De Boel', 'Thibault', 'Montignies-sur-Sambre', '6061'),
('De Bosscher', 'Alain', 'Gilly', '6060'),
('De Bouver', 'Hervé', 'Courcelles', '6180'),
('De Bouver', 'Stéphanie', 'Courcelles', '6180'),
('De Breucker', 'Eric', 'Gerpinnes', '6280'),
('De Bruyn', 'Christine', 'Gosselies', '6041'),
('De Bruyn', 'Jean-François', 'Gerpinnes', '6280'),
('De Cian', 'Manuela', 'Gosselies', '6041'),
('De Cock', 'Jean-Louis', 'Charleroi', '6000'),
('De Cock', 'Thibault', 'Gerpinnes', '6280'),
('De Cooman', 'Marc', 'Gosselies', '6041'),
('De Cort', 'Julie', 'Gosselies', '6041'),
('De Coster', 'Christophe', 'Gilly', '6060'),
('De Coster', 'Emmanuelle', 'Gilly', '6060'),
('De Coster', 'François', 'Gilly', '6060'),
('De Coster', 'Gilles', 'Gilly', '6060'),
('De Coster', 'Jean-François', 'Gilly', '6060'),
('De Coster', 'Johan', 'Gilly', '6060'),
('De Coster', 'Laurent', 'Gilly', '6060'),
('De Coster', 'Pierre', 'Gilly', '6060'),
('De Coster', 'Stéphane', 'Gilly', '6060'),
('De Cremer', 'François', 'Montignies-sur-Sambre', '6061'),
('De Cremer', 'Jean-Claude', 'Montignies-sur-Sambre', '6061'),
('De Croock', 'Frédéric', 'Courcelles', '6180'),
('De Decker', 'Michaël', 'Gosselies', '6041'),
('De Donder', 'Olivier', 'Gosselies', '6041'),
('De Dycker', 'Frédéric', 'Gerpinnes', '6280'),
('De Fays', 'Bernard', 'Gilly', '6060'),
('De Fays', 'Caroline', 'Gilly', '6060'),
('De Fays', 'François', 'Gilly', '6060'),
('De Fays', 'Jean-Philippe', 'Gilly', '6060'),
('De Fays', 'Pierre', 'Gilly', '6060'),
('De Fays', 'Stéphane', 'Gilly', '6060'),
('De Fays', 'Vincent', 'Gilly', '6060'),
('De Fays', 'Xavier', 'Gilly', '6060'),
('De Felice', 'Sylvain', 'Montignies-sur-Sambre', '6061'),
('De Filippis', 'Angela', 'Montignies-sur-Sambre', '6061'),
('De Gaspéri', 'Eric', 'Frasnes-lez-Gosselies', '6210'),
('De Geest', 'David', 'Charleroi', '6000'),
('De Geest', 'Sylvie', 'Charleroi', '6000'),
('De Gelder', 'Alexandre', 'Gilly', '6060'),
('De Gendt', 'Johan', 'Gosselies', '6041'),
('De Glas', 'Catherine', 'Gilly', '6060'),
('De Greef', 'Laurence', 'Montignies-sur-Sambre', '6061'),
('De Groote', 'Christophe', 'Gilly', '6060'),
('De Gucht', 'Catherine', 'Charleroi', '6000'),
('De Gucht', 'Georges', 'Gerpinnes', '6280'),
('De Gucht', 'Pascal', 'Charleroi', '6000'),
('De Gucht', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Damien', 'Gerpinnes', '6280'),
('De Hantsetters', 'Didier', 'Gerpinnes', '6280'),
('De Hantsetters', 'Elodie', 'Gerpinnes', '6280'),
('De Hantsetters', 'Joël', 'Gerpinnes', '6280'),
('De Hantsetters', 'Luc', 'Gerpinnes', '6280'),
('De Hantsetters', 'Ludovic', 'Gerpinnes', '6280'),
('De Hantsetters', 'Michaël', 'Gerpinnes', '6280'),
('De Hantsetters', 'Patricia', 'Gerpinnes', '6280'),
('De Hantsetters', 'Philippe', 'Gerpinnes', '6280'),
('De Hantsetters', 'Rudy', 'Gerpinnes', '6280'),
('De Hantsetters', 'Sandra', 'Gerpinnes', '6280'),
('De Hantsetters', 'Thierry', 'Gerpinnes', '6280'),
('De Hantsetters', 'Valérie', 'Gerpinnes', '6280'),
('De Hantsetters', 'Virginie', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
('De Hantsetters', 'Yves', 'Gerpinnes', '6280'),
